#!/bin/bash
#
# oni-install
# Copyright (c) 2015 Robert Calvert <http://robert.calvert.io>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>


############################################
# Set variables
############################################

SCRIPT_DIR=$(readlink -f $(dirname $0))

############################################
# Show the welcome message
############################################
clear
echo ""
echo " _____     _ "
echo "|     |___|_|"
echo "|  |  |   | |"
echo "|_____|_|_|_| "
echo ""
echo "An Openbox Netinstall script for Debian."
echo ""

############################################
# Confirm before running the install
############################################
read -r -p "Run the install now? [y/N] " rINSTALL
case $rINSTALL in
    [yY][eE][sS]|[yY])
    
        ############################################
		# Update the repositories
		############################################
		clear
		echo "Updating repositories..."
		echo ""
		sleep 1s
		sudo apt-get update
		echo ""
		echo "DONE"
		echo ""
		sleep 2s

		############################################
		# Perform Dist Upgrade
		############################################
		clear
		echo "Performing dist upgrade..."
		echo ""
		sleep 1s
		sudo apt-get -y dist-upgrade
		echo ""
		echo "DONE"
		echo ""
		sleep 2s

		############################################
		# Install Desktop
		############################################
		clear
		echo "Installing Desktop packages..."
		echo ""
		sleep 1s
		sudo apt-get -y install xorg openbox obmenu lxpanel tint2 conky i3lock
		echo ""
		echo "DONE"
		echo ""
		sleep 2s
		
		############################################
		# Install Core packages
		############################################
		clear
		echo "Installing Core packages..."
		echo ""
		sleep 1s
		sudo apt-get -y install synaptic apt-xapian-index zenity xfce4-power-manager fdpowermon powertop arandr dunst gnome-system-log lm-sensors
		sudo apt-get -y install terminator thunar thunar-volman thunar-archive-plugin xarchiver gdebi geany galculator gimp catfish clipit lxtask gsimplecal bleachbit clamtk xpdf viewnior tcplay
		echo ""
		echo "DONE"
		echo ""
		sleep 2s
		
		############################################
		# Install Media packages
		############################################
		clear
		echo "Installing Media packages..."
		echo ""
		sleep 1s
		sudo apt-get -y install alsa-base gstreamer0.10-alsa volumeicon-alsa
		sudo apt-get -y install pulseaudio pavucontrol xfce4-volumed
		sudo apt-get -y install vlc audacious xfce4-screenshooter scrot xfburn tumbler-plugins-extra imagemagick
		echo ""
		echo "DONE"
		echo ""
		sleep 2s
		
		############################################
		# Install Network packages
		############################################
		clear
		echo "Installing Network packages..."
		echo ""
		sleep 1s
		sudo apt-get -y install wicd chromium filezilla deluge remmina
		echo ""
		echo "DONE"
		echo ""
		sleep 2s
		
		############################################
		# Install Development packages
		############################################
		clear
		echo "Installing Development packages..."
		echo ""
		sleep 1s
		sudo apt-get -y install git git-gui kdiff3-qt
		echo ""
		echo "DONE"
		echo ""
		sleep 2s
		
		############################################
		# Install Theme packages
		############################################
		clear
		echo "Installing Theme packages..."
		echo ""
		sleep 1s
		sudo apt-get -y install lxappearance nitrogen gtk2-engines-murrine
		echo ""
		echo "DONE"
		echo ""
		sleep 2s

		############################################
		# Apply the System configurations
		############################################
		clear
		echo "Applying the System configurations..."
		echo ""
		sleep 1s
		sudo cp -R $SCRIPT_DIR/system/etc/. /etc/
		sudo cp -R $SCRIPT_DIR/system/usr/. /usr/
		sudo cp -R $SCRIPT_DIR/system/opt/. /opt/
		sudo cp -R $SCRIPT_DIR/system/root/. /root/
		cp -R $SCRIPT_DIR/system/home/. /home/$USER/
		sudo ln -s /opt/themes/Airborne /usr/share/themes/Airborne
		sudo ln -s /opt/themes/Minimal /usr/share/themes/Minimal
		mkdir /home/$USER/bin
		mkdir /home/$USER/Development
		mkdir /home/$USER/Encrypted
		echo ""
		echo "DONE"
		echo ""
		sleep 2s
			
		############################################
		# Run sensors detect
		############################################
		clear
		echo "Running sensors-detect..."
		echo ""
		sleep 1s
		sudo sensors-detect
		echo ""
		echo "DONE"
		echo ""
		sleep 2s
		
		############################################
		# Perform autoremove
		############################################
		clear
		echo "Performing autoremove..."
		echo ""
		sleep 1s
		sudo apt-get -y autoremove
		echo ""
		echo "DONE"
		echo ""
		sleep 2s

		############################################
		# Perform clean
		############################################
		clear
		echo "Performing clean..."
		echo ""
		sleep 1s
		sudo apt-get clean
		echo ""
		echo "DONE"
		echo ""
		sleep 2s

		############################################
		# Show the done message
		############################################
		clear
		echo "Install complete..."
		echo ""

		############################################
		# Prompt for reboot
		############################################
		read -r -p "Reboot the system now? [y/N] " rREBOOT
		case $rREBOOT in
			[yY][eE][sS]|[yY])
				sudo reboot
				exit
			;;

		*)
			exit
			;;

		esac
        ;;

	[nN][oO]|[nN])

		############################################
		# Exit the install
		############################################
		exit
		;;

    *)

		############################################
		# Loop back into the install
		############################################
		$0
        ;;

esac
