#!/bin/bash
#
# oni-install
# Copyright (c) 2018 Robert Calvert <http://robert.calvert.io>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

############################################
# Set variables
############################################

SCRIPT_DIR=$(readlink -f "$(dirname "$0")")

############################################
# Show the welcome message
############################################
echo ""
echo " _____     _ "
echo "|     |___|_|"
echo "|  |  |   | |"
echo "|_____|_|_|_| "
echo ""
echo "An Openbox Netinstall script for Debian."
echo ""

############################################
# Confirm before running the install
############################################
read -r -p "Run the install now? [y/N] " rINSTALL
case $rINSTALL in
    [yY][eE][sS]|[yY])
        
        ############################################
        # Update the repositories
        ############################################
        echo "Updating repositories..."
        echo ""
        sudo apt update
        echo ""
        
        ############################################
        # Perform Dist Upgrade
        ############################################
        echo "Performing dist upgrade..."
        echo ""
        sudo apt -y dist-upgrade
        echo ""
        
        ############################################
        # Apply the System configurations
        ############################################
        echo "Applying the System configurations..."
        echo ""
        sudo cp -R "$SCRIPT_DIR"/system/etc/. /etc/
        sudo cp -R "$SCRIPT_DIR"/system/usr/. /usr/
        sudo cp -R "$SCRIPT_DIR"/system/root/. /root/
        cp -R "$SCRIPT_DIR"/system/home/. /home/"$USER"/
        mkdir /home/"$USER"/bin
        mkdir /home/"$USER"/Development
        mkdir /home/"$USER"/Encrypted
        echo ""
        
        ############################################
        # Build the install command
        ############################################
        COMMAND="sudo apt -y install"
        
        ############################################
        # Desktop
        ############################################
        COMMAND+=" xorg openbox obmenu lxpanel tint2 conky i3lock suckless-tools"
        
        ############################################
        # Core
        ############################################
        COMMAND+=" synaptic apt-xapian-index zenity xfce4-power-manager fdpowermon powertop arandr dunst gnome-system-log lm-sensors"
        COMMAND+=" terminator thunar thunar-volman thunar-archive-plugin xarchiver gdebi geany galculator gimp catfish clipit lxtask gsimplecal bleachbit clamtk xpdf viewnior tcplay"
        
        ############################################
        # Media
        ############################################
        COMMAND+=" gstreamer1.0-alsa volumeicon-alsa"
        COMMAND+=" pulseaudio pavucontrol" # xfce4-volumed
        COMMAND+=" vlc audacious xfce4-screenshooter scrot xfburn tumbler-plugins-extra imagemagick"
        
        ############################################
        # Network
        ############################################
        COMMAND+=" wicd chromium filezilla deluge avahi-daemon" # remmina
        
        ############################################
        # Development
        ############################################
        COMMAND+=" git git-gui kdiff3-qt"
        
        ############################################
        # Theme
        ############################################
        COMMAND+=" lxappearance nitrogen arc-theme qt5-style-plugins"
        
        ############################################
        # Install the packages
        ############################################
        set -e

        echo "Installing packages..."
        echo ""
        $COMMAND
        echo ""
        
        ############################################
        # Run sensors detect
        ############################################
        echo "Running sensors-detect..."
        echo ""
        sudo sensors-detect
        echo ""
        
        ############################################
        # Perform autoremove
        ############################################
        echo "Performing autoremove..."
        echo ""
        sudo apt -y autoremove
        echo ""
        
        ############################################
        # Perform clean
        ############################################
        echo "Performing clean..."
        echo ""
        sudo apt clean
        echo ""
        
        ############################################
        # Show the done message
        ############################################
        echo "Install complete..."
        echo ""
        
        ############################################
        # Prompt for reboot
        ############################################
        read -r -p "Reboot the system now? [y/N] " rREBOOT
        case $rREBOOT in
            [yY][eE][sS]|[yY])
                sudo reboot
                exit
            ;;
            
            *)
                exit
            ;;
            
        esac
    ;;
    
    [nN][oO]|[nN])
        
        ############################################
        # Exit the install
        ############################################
        exit
    ;;
    
    *)
        
        ############################################
        # Loop back into the install
        ############################################
        $0
    ;;
    
esac
